[project]
name = "eps-ui"
version = "0.1.4"
description = "Django app amb templates i estàtics corporatius EPS UIB."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [{ name = "Biel Cardona", email = "bielcardona@gmail.com" }]
dependencies = [
    "Django>=3.2",
]

[build-system]
requires = ["uv_build>=0.7"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
